name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: write-all

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Install dependencies
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r books/requirements.txt

    - name: Clean previous build
      run: |
        jupyter-book clean books/ || true

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build books

    - name: Verify build output
      run: |
          echo "Current directory:"
          pwd
          echo "Repository root:"
          ls -la
          echo "books directory:"
          ls -la books
          echo "books/_build directory:"
          ls -la books/_build
          echo "books/_build/html directory:"
          ls -la books/_build/html
          
    # Push the book's HTML to github-pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./books/_build/html
        force_orphan: true
